### ISSUE TITLE
ShowLink  bug with port monitor

### ISSUE THREAD

**Issue by KevinZonda** [geekyouth/uptime-status#5]
I tried to set a port monitor and turn the ShowLink on

Then the status link will redirect to $StatusSiteUrl/$PortMonitorSite

Here's a sample:

```
Monitor: 1.1.1.1:443
Status page: a.com
```

Click the link in the status page

I will visit `a.com/1.1.1.1`

**Comment by geekyouth** [comment]
@KevinZonda 

I think your should commit your issue to https://uptimerobot.com/ offical.

Because this project dependency that.

**Comment by KevinZonda** [comment]
Sure, thx
