### ISSUE TITLE
Can you provide the real source code of this project?

### ISSUE THREAD

**Issue by KevinZonda** [geekyouth/uptime-status#6]
I think the code of this repo has been compiled. It is build by node.js?

**Comment by ghost** [comment]
Hello Kevin,
The original source code written in node.js is here: [https://github.com/yb/uptime-status](https://github.com/yb/uptime-status)

**Comment by KevinZonda** [comment]
> Hello Kevin,
> The original source code written in node.js is here: https://github.com/yb/uptime-status

Thanks a lot!
